//

import type { Metadata } from "next";

//importación Google Fonts
import { Lora, Pacifico } from "next/font/google";

import "./globals.css";
import { Navbar } from "@/components";

//Google Fonts
const lora = Lora({ 
  subsets: ['latin'],
  weight: "400" 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.className} h-screen px-8`}>
        <Navbar />
        <div className="flex justify-between">
          <div className="w-1/3">
          </div>
          <div className="w-2/3 p-4 h-screen">
            {children}
          </div>

        </div>

      </body>
    </html>
  );
}
