//

import type { Metadata } from "next";

//importación Google Fonts
import { Poppins } from "next/font/google";

import "./globals.css";
import { Navbar, Footer } from "@/components";


//Google Fonts
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${poppins.className} h-screen flex flex-col px-8`}>
        <Navbar />
        <div className="flex justify-between h-full">
          <div className="w-1/3">
          </div>
          <div className="w-2/3 p-10">
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
